<a href="https://colab.research.google.com/github/MiguelUTEC26/etl-data-pipeline/blob/main/Aseguradora.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [7]:
from sqlalchemy import create_engine

In [8]:
import pandas as pd

In [9]:
url = "https://raw.githubusercontent.com/MiguelUTEC26/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"
df = pd.read_csv(url)

df.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [10]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            13 non-null     object
 3   rating_riesgo   12 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

In [11]:
aseguradora = df.copy()

aseguradora.columns = aseguradora.columns.str.strip().str.lower()

for col in aseguradora.select_dtypes(include='object').columns:
    aseguradora[col] = aseguradora[col].astype(str).str.strip()

aseguradora = aseguradora.replace(r'^\s*$', pd.NA, regex=True)

aseguradora['pais'] = aseguradora['pais'].str.lower()
aseguradora['nombre'] = aseguradora['nombre'].str.lower()

aseguradora = aseguradora.drop_duplicates()

In [12]:
validos = aseguradora[
    aseguradora['pais'].notna() &
    aseguradora['rating_riesgo'].notna()
].copy()

rechazados = aseguradora[
    aseguradora['pais'].isna() |
    aseguradora['rating_riesgo'].isna()
].copy()

In [13]:
def motivo(row):

    motivos = []

    if pd.isna(row['pais']):
        motivos.append("pais_vacio")

    if pd.isna(row['rating_riesgo']):
        motivos.append("riesgo_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [14]:
validos.to_csv("aseguradora_curated.csv", index=False)

rechazados.to_csv("aseguradora_rejects.csv", index=False)

In [15]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_c7ck_user:kFoJ2P6ViVJGqvzaVHFeHuuMqEThO1y3@dpg-d6qu3vc50q8c73bpda60-a.oregon-postgres.render.com/etl_seguros_c7ck"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [18]:
validos.to_sql(
    'aseguradora_curated',
    engine,
    if_exists='append',
    index=False
)
rechazados.to_sql(
    'aseguradora_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [20]:
pd.read_sql(
"SELECT * FROM aseguradora_curated LIMIT 10",
engine
)

   id_aseguradora          nombre         pais rating_riesgo
0               1   aseguradora 1   costa rica          Alto
1               2   aseguradora 2  el salvador          Bajo
2               3   aseguradora 3  el salvador           nan
3               4   aseguradora 4   costa rica         Medio
4               5   aseguradora 5   elsalvador             B
5               6   aseguradora 6          nan         Medio
6               7   aseguradora 7    guatemala          Alto
7               8   aseguradora 8       panamá          Bajo
8               9   aseguradora 9          nan          Bajo
9              10  aseguradora 10       panamá           nan

In [21]:
pd.read_sql(
"SELECT * FROM aseguradora_rejects LIMIT 10",
engine
)

Empty DataFrame
Columns: [id_aseguradora, nombre, pais, rating_riesgo, motivo_rechazo]
Index: []